name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'varunsridharan'
          COUNT: 8
          STYLE: "blog-grid-4"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
